trigger:
  branches:
    include:
      - main

jobs:
  - job: EchoCommandsJob
    displayName: Echo Commands
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - script: |
          echo "This is an echo command"
          echo "Hello, World!"
        displayName: 'Echo Messages'

      - script: |
          echo "Executing a complex command"
          echo "This command has multiple lines"
          echo "Line 1"
          echo "Line 2"
          echo "Line 3"
        displayName: 'Complex Command'
