#test 
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Starting the pipeline...'
  displayName: 'Step 1'

- script: echo 'Running build tasks...'
  displayName: 'Step 2'

- script: echo 'Running tests...'
  displayName: 'Step 3'

- script: echo 'Publishing artifacts...'
  displayName: 'Step 4'
